[package]
name = "rpnc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
argparse = "0.2.2"
atty = "0.2.14"
rand = "0.8.5"
